apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-edge-daemonset
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana-edge
  template:
    metadata:
      labels:
        app: grafana-edge
    spec:
      # initContainers:
      #   - name: take-ownership
      #     image: busybox
      #     command: ["chown", "-R", "472:472", "/var/lib/grafana"]
      #     volumeMounts:
      #       - name: grafana-storage
      #         mountPath: "/var/lib/grafana"
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              hostPort: 3000
          # volumeMounts:
          #   - mountPath: "/var/lib/grafana"
          #     name: grafana-storage
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin1234"
      nodeSelector:
        role: edge_worker
